spring:
  datasource:
    url: jdbc:mysql://localhost:3306/his?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 994215
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181